config/routes.rb
Rails.application.routes.draw do

  resources :charges
  resources :genres

  resources :movies do
    resources :reviews
  end
  resources :actors
  resources :users
  resources :sessions

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"

  root to: "movies#index"

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  has_many :movies, through: :roles
end

app/models/dog.rb
class Dog

  def speak
    "woof"
  end

  def name
    "Fido"
  end

  def save
    "WTF"
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base
end

app/models/monkey.rb
class Monkey < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :studio
  has_many :roles
  has_many :reviews
  has_many :actors, through: :roles

  validates :name, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  has_many :movies
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  skip_before_action :require_user, only: :show

  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find_by(id: params["id"])
    @roles = @actor.roles
  end

  def new
    @actor = Actor.new
  end

  def create
    actor_params = params.require(:actor).permit(:name)
    @actor = Actor.create(actor_params)
    
    # read the uploaded file
    file = params["actor"]["photo"]
    file_data = file.read

    # write the uploaded file to a new file somewhere
    the_file = Rails.root.join("public", "images", "#{@actor.id}.jpg")
    File.open(the_file, "wb") do |f|
      f.write(file_data)
    end
    
    redirect_to actors_path
  end

  def edit
    @actor = Actor.find_by(id: params["id"])
  end

  def update
    actor_params = params.require(:actor).permit(:name)
    @actor = Actor.find_by(id: params["id"])
    @actor.update(actor_params)
    redirect_to actors_path
  end

  def destroy
    @actor = Actor.find_by(id: params["id"])
    @actor.destroy
    redirect_to actors_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :require_user

  def current_user
    User.find_by(id: session["user_id"])
  end

  def require_user
    if current_user.nil?
      redirect_to new_session_path
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    redirect_to movies_path, notice: "Thanks for the dough!"

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :require_user, only: [:index, :show]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find_by(id: params["id"])
    @roles = @movie.roles
  end

  def edit
    @movie = Movie.find_by(id: params["id"])
  end

  def update
    movie_params = params.require(:movie).permit!
    @movie = Movie.find_by(id: params["id"])
    @movie.update(movie_params)
    if @movie.valid?
      redirect_to movies_path
    else
      render text: "FAIL"
    end
  end

  def destroy
    @movie = Movie.find_by(id: params["id"])
    @movie.destroy
    redirect_to movies_path
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie

  def new
    @review = Review.new
  end

  def create
    review_params = params.require(:review).permit(:body, :rating)
    @review = @movie.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @movie, notice: "Thanks for the review!"
    else
      render "new"
    end
  end

  def find_movie
    @movie = Movie.find_by(id: params["movie_id"])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :require_user

  def create
    # params["email"] => the email address
    # params["password"] => the password
    # Do authentication
    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful

    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      redirect_to root_path, notice: "Sweet, you're in!"
    else
      redirect_to root_path, alert: "No way man."
    end

  end

  def destroy
    # Do sign-out
    session["user_id"] = nil
    redirect_to root_path, notice: "See ya later!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit!
    @user = User.create(user_params)
    if @user.valid?
      redirect_to users_path, notice: "Sweet"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def update
    user_params = params.require(:user).permit!
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def price_for(movie)
    number_to_currency(movie.price.to_d / 100) if movie.price
  end

  def stars_for(review)
    stars = ""
    review.rating.times do
      stars = stars + '<i class="fa fa-star"></i>'
    end
    stars.html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/actors/_form.html.erb
<%= form_for @actor do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  <%= form.button title, class: "btn btn-success" %>
<% end %>

app/views/actors/edit.html.erb
<%= render "form", title: 'Update Actor' %>

app/views/actors/index.html.erb
<h3 class="page-header">
  All Actors
  <span class="pull-right">
    <%= link_to "New Actor", new_actor_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %> <%= link_to "Edit", edit_actor_path(actor) %> <%= link_to "Delete", actor_path(actor), method: :delete, data: { confirm: 'Are you really really really sure?' } %></li>
  <% end %>
</ul>

app/views/actors/new.html.erb
<%= render "form", title: 'Create Actor' %>

app/views/actors/show.html.erb
<p>
  <%= image_tag "#{@actor.id}.jpg", style: 'width:300px' %>
</p>

<h1><%= @actor.name %></h1>

<h3>Appears In</h3>

<ul>
  <% @roles.each do |role| %>
    <li><%= link_to role.movie.name, movie_path(role.movie) %></li>
  <% end %>
</ul>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $25000.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Superman III"
          data-amount="2500000"></script>
<% end %>

app/views/movies/edit.html.erb
<% if @movie.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this movie from being saved:</h2>
    <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @movie do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :studio_id %>
    <%= form.collection_select :studio_id, Studio.order(:name), :id, :name, { include_blank: true }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.text_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: "form-control", rows: 5 %>
  </div>
  <div class="form-group">
    <%= form.label :year_released %>
    <%= form.text_field :year_released, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :runtime %>
    <%= form.text_field :runtime, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :format %>
    <%= form.text_field :format, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <%= form.button 'Create Movie', class: "btn btn-success" %>
<% end %>

app/views/movies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div id="chart" style="height: 400px;"></div>
  </div>
</div>
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(movie.image), movie %>
        <div class="caption">
          <h3><%= link_to movie.name, movie %></h3>
          <p><%= movie.summary %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(function () { 
    $('#chart').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: 'Movie Runtime, 2014'
      },
      xAxis: {
        categories: ['Runtime']
      },
      yAxis: {
        title: {
          text: 'Minutes'
        }
      },
      legend: {
        enabled: false
      },
      plotOptions: {
        column: {
          groupPadding: 1.0
        }
      },
      series: [
        {
          name: 'Jane',
          data: [1, 0, 4]
        }, 
        {
          name: 'John',
          data: [5, 7, 3]
        }
      ]
    });
  });
</script>

app/views/movies/new.html.erb
<%= form_for @movie do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Search for Movie', class: "btn btn-success" %>
<% end %>

app/views/movies/show.html.erb
<h1 class="title">
  <%= @movie.name %>
  <span class="rating"><%= @movie.rating %></span>
</h1>

<div class="row">
  <div class="col-md-3 text-center">
    <p><%= image_tag @movie.image, class: "poster" %></p>
    <p>
      <a href="#" class="btn btn-sm btn-success">
        <i class="fa fa-shopping-cart"></i> 
        <%= price_for(@movie) %> 
        Buy in HD
      </a>
    </p>
    <p><strong>Genre:</strong> <%= @movie.genre %></p>
    <p><strong>Released:</strong> <%= @movie.year_released %></p>
  </div>
  <div class="col-md-4 summary">
    <h2>Summary</h2>
    <p>
      <%= @movie.summary %>
    </p>
  </div>
  <div class="col-md-3 actors">
    <h2>Cast</h2>
    <ul class="list-unstyled">
      <% @roles.each do |role| %>
        <li><%= link_to role.actor.name, actor_path(role.actor) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <h3>Reviews</h3>
    <% @movie.reviews.each do |review| %>
      <h4><%= review.user.name %> <%= stars_for(review) %></h4>
      <p><%= review.body %></p>
    <% end %>

    <%= link_to "Write a Review", new_movie_review_path(@movie), class: 'btn btn-success' %>
  </div>
</div>

<div class="row">
  <div class="col-md-9 col-md-offset-3 reviews">
    <h2 class="page-header">Information</h2>
    <table class="table table-striped table-bordered">
      <tr>
        <td><strong>Run Time</strong></td>
        <td><%= @movie.runtime %></td>
      </tr>
    </table>
  </div>
</div>

app/views/reviews/new.html.erb
<%= form_for [@movie, @review] do |form| %>
  <div class="form-group">
    <%= form.label :rating %>
    <%= form.select :rating, [1,2,3,4,5], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <%= form.button 'Post Your Review', class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Update', class: "btn btn-success" %>
<% end %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- 
  Finish the signup form
  User:
    email: string
    password: string
    name: string
-->

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <%= form.button 'Sign Up', class: "btn btn-success" %>
<% end %>